### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by mfrey** [pkittenis/parallel-ssh#19]
Hi,

I'm wondering if you would be interested in python3 support? If there are no major show stoppers you are aware of, I would like to try to port it to python 3 and submitting a pull request.

Best,
 Michael

P.S.: I've found your package via google and installed it via pip-3.2 (I wasn't aware that it is possible to install python2 packages via a pip of version 3) and was wondering why I couldn't execute it in a python3.2 shell. And just for the sake of clarity, the first resulting issue is:
```python
Python 3.2.3 (default, Feb 20 2013, 17:02:41) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pssh import ParallelSSHClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.2/dist-packages/pssh.py", line 183
    except sock_gaierror, ex:
                        ^
SyntaxError: invalid syntax
```
which should be
```
except sock_gaierror as ex:
```

**Comment by mfrey** [comment]
Hrm. This would acutually break the python2 support. Suggestions?

**Comment by pkittenis** [comment]
Yes, gevent does not support python 3 and is a blocker. ParallelSSH code is easily translated with `2to3`.
