### ISSUE TITLE
Decouple ParallelSSH from Openssh config

### ISSUE THREAD

**Issue by pkittenis** [pkittenis/parallel-ssh#20]
ParallelSSH currently attempts to read and parse an OpenSSH compatible config in `~/.ssh` and/or `/etc/ssh/config`.

This allows for per-host user and host name configurations but couples ParallelSSH with OpenSSH and its configs.

Allow for per host authentication configuration to be provided to ParallelSSH so that connecting to multiple hosts with differing authentication mechanisms is both possible and not dependent on OpenSSH configuration files.

**Comment by lordnynex** [comment]
:+1:

**Comment by pkittenis** [comment]
Eg:

```
client = ParallelSSHClient(hosts=['host1', 'host2'], 
    host_config={ 'host1': {'port' : 2222, 'private_key': 'my_key.pem'}, 
                  'host2': {'port' : 2223, 'private_key': 'my_other_key.pem'}})
```
