### ISSUE TITLE
duplicate command output

### ISSUE THREAD

**Issue by nchammas** [pkittenis/parallel-ssh#27]
Consider this script:

```python
from __future__ import print_function

from pssh import ParallelSSHClient

hosts = ['localhost']
client = ParallelSSHClient(hosts)
output = client.run_command('date')

for host in output:
    for line in output[host]['stdout']:
        print("[{h}] {o}".format(h=host, o=line))
```

This is what I get when I run it locally:

```
$ python --version
Python 2.7.9
$ pip show parallel-ssh
---
Name: parallel-ssh
Version: 0.70.2
Location: /usr/local/lib/python2.7/site-packages
Requires: paramiko, gevent
$ python parallel-ssh-example.py 
[localhost]	Fri Mar 27 18:30:26 EDT 2015
[localhost] Fri Mar 27 18:30:26 EDT 2015
```

The output is unexpectedly printed out twice instead of once. Also, the first copy of the output strangely has a tab instead of a regular space at the beginning. (As in, `[localhost] tab Fri...`. The tab looks like a space when GitHub renders the output here.)

Is this a bug, or is there something I am doing incorrectly?

**Comment by pkittenis** [comment]
The output without tab is the print statement in the example script.

The output with tab is from the `pssh.host_logger` logger which is enabled by default - see [get_output docs](http://parallel-ssh.readthedocs.org/en/latest/#pssh.ParallelSSHClient.get_output)

For example, with no print:

```python
for host in output:
       for line in output[host]['stdout']:
               pass
[localhost]	Tue Mar 31 11:13:20 BST 2015
```

Disable `host_logger`, no output without print:

```python
import logging
logger = logging.getLogger('pssh.host_logger')
for handler in logger.handlers: logger.removeHandler(handler)

output = client.run_command('date')
for host in output:
       for line in output[host]['stdout']:
               pass
   ....:     
No handlers could be found for logger "pssh.host_logger"

output = client.run_command('date')
for host in output:
        for line in output[host]['stdout']:
                print("[{h}] {o}".format(h=host, o=line))
   ....:         
[localhost] Tue Mar 31 11:15:15 BST 2015
```

**Comment by nchammas** [comment]
Ah, that explains things.

@pkittenis Would it make sense to turn this logging off by default?

I can't speak for others, but I found it confusing that there was stuff being printed without my explicit instruction to do so. Perhaps there is a precedent for doing things like this that I am not aware of.

**Comment by pkittenis** [comment]
I wouldn't be opposed to not enabling it by default - it really depends on what most users expect the default behaviour to be.

In most real world use-cases it is expected that users will want output of commands being run, similar to a build server having console output available when you click on the job being run.

For this reason, host logging is enabled by default.

That said, I do agree that libraries should not have handlers attached to their loggers by default. 

Perhaps a single function to enable logging would be good and the handler not attached by default. 

Then user only needs to run that one function to enable logging if desired.

**Comment by pkittenis** [comment]
Have raised #29 to get some feedback on this

**Comment by nchammas** [comment]
The point about library use makes total sense. I'll follow #29 to see what others have to say about the matter.
