### ISSUE TITLE
Allow output gathering for working hosts when one or more hosts have failures

### ISSUE THREAD

**Issue by jasonfharris** [pkittenis/parallel-ssh#32]
When executing say client.run_command(...) over many hosts there is the possibility that a single host has problems. Maybe there is a nice way to recover when a single hosts fails? but I didn't see how to so this easily at present. Right now an exception is thrown and things stop.  A nice way to recover would be good. In fact our example actually tests some of the hosts and sometimes they don't respond or they are switched off, etc. etc.

**Comment by pkittenis** [comment]
Hi there, thank you for the feedback.

You are correct, on any errors command execution on any remaining hosts in the host list will stop.

Can add a `stop_on_errors` or similar flag to turn on/off whether to stop or continue with host list on any host specific errors.

Exceptions will still need to be caught.

**Comment by pkittenis** [comment]
Have started adding a keyword argument to turn on/off exception raising in `run_command`.

This will allow you to make a decision on whether or not you want exceptions raised on errors or placeholder output containing exception object returned instead, along output for the remainder of the host list.

NB - `return` and `raise` are mutually exclusive in Python. A function that raises an exception cannot return and vice versa. It is not possible to simultaneously raise an exception on error while also returning output.

**Comment by pkittenis** [comment]
Finally got some time to finish this at the [output](https://github.com/pkittenis/parallel-ssh/tree/output) branch.

There is a back-wards incompatible change to a public API function, ``get_output``, so this change has been moved back to the 0.80 release which will be out once documentation has been updated to reflect this and other changes.

Feel free to install the [output](https://github.com/pkittenis/parallel-ssh/tree/output) branch in the meantime but **be aware** that not all exceptions are yet being tested for partial failures and looking at the code it is likely that ``UnknownHostException`` and ``ConnectionErrorException`` will cause host output for the failed host to be lost - but not output for rest of host list.

Exhaustive tests for this new behaviour will be in before output branch is merged.

With the changes in that branch, to cause ``ParallelSSHClient`` to *not* stop on errors, call ``run_command`` like:

```python
output = client.run_command('cmd', stop_on_errors=False)
```

If a host in the host list has an exception, its output will contain an ``exception`` key with the exception object as its value.

If you have been using ``get_output`` directly, interface has changed to:

```python
output = {}
for cmd in cmds:
    # output variable gets updated in-place for every cmd's output
    client.get_output(cmd, output)
```

from

```python
output = client.get_output(commands=cmds)
```
