### ISSUE TITLE
unable to install with pip, requirements.txt missing

### ISSUE THREAD

**Issue by MichaelKofler** [pkittenis/parallel-ssh#38]
I am unable to install parallel-ssh (tested with current Ubuntu, Debian + Fedora). On Debian:

apt-get install python-pip
pip install parallel-ssh
Downloading/unpacking parallel-ssh
  Downloading parallel-ssh-0.80.0.tar.gz
  Running setup.py (path:/tmp/pip-build-feBbyp/parallel-ssh/setup.py) egg_info for package parallel-ssh
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-feBbyp/parallel-ssh/setup.py", line 26, in <module>
        install_requires = open('requirements.txt').readlines(),
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-feBbyp/parallel-ssh/setup.py", line 26, in <module>

    install_requires = open('requirements.txt').readlines(),

IOError: [Errno 2] No such file or directory: 'requirements.txt'

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-feBbyp/parallel-ssh
Storing debug log for failure in /home/kofler/.pip/pip.log

------------------------------------------

This is /home/kofler/.pip/pip.log:

------------------------------------------------------------ /tmp/pip-build-feBbyp/parallel-ssh
/usr/bin/pip run on Mon Oct  5 08:20:25 2015
Downloading/unpacking parallel-ssh
  Getting page https://pypi.python.org/simple/parallel-ssh/", line 122, in main
  URLs to search for versions for parallel-ssh:
  * https://pypi.python.org/simple/parallel-ssh/mands/install.py", line 290, in run
  Analyzing links from page https://pypi.python.org/simple/parallel-ssh/e, bundle=self.bundle)
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.1.tar.gz#md5=332d3d16c740883afd01d680a13493e2 (from https://pypi.python.org/simple/parallel-ssh/), version: 0.1
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.2.tar.gz#md5=746ea512cf1b8dc2952eabd6aeb50e8d (from https://pypi.python.org/simple/parallel-ssh/), version: 0.2
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.3.tar.gz#md5=5d8019f26580f348377cae707555badb (from https://pypi.python.org/simple/parallel-ssh/), version: 0.3
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.4.tar.gz#md5=b6c1f6c071aa4000f8fc82a3c548cd8c (from https://pypi.python.org/simple/parallel-ssh/), version: 0.4
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.5.tar.gz#md5=7e4309b54e7b3763717f419c5eca5013 (from https://pypi.python.org/simple/parallel-ssh/), version: 0.5
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.6.tar.gz#md5=db3acbacaa0b9036b5a16f89b00c3e27 (from https://pypi.python.org/simple/parallel-ssh/), version: 0.6
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.61.tar.gz#md5=bdd1944fa804f8d70fc72562b460f69f (from https://pypi.python.org/simple/parallel-ssh/), version: 0.61
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.7.tar.gz#md5=56d045bb3bb086728b7d264db93998a9 (from https://pypi.python.org/simple/parallel-ssh/), version: 0.7
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.70.1.tar.gz#md5=8c4600fec796d7f50fec5236654e225c (from https://pypi.python.org/simple/parallel-ssh/), version: 0.70.1
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.70.2.tar.gz#md5=24744eb45c3e622d80edaa10e94f1593 (from https://pypi.python.org/simple/parallel-ssh/), version: 0.70.2
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.70.3.tar.gz#md5=056f04c6c0ec9ced8e4f2623fefab399 (from https://pypi.python.org/simple/parallel-ssh/), version: 0.70.3
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.70.4.tar.gz#md5=9755cd3ca1fd806e82c35b57f170cb3e (from https://pypi.python.org/simple/parallel-ssh/), version: 0.70.4
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.70.tar.gz#md5=2ff37d347845d3d6ed14567a8b85393b (from https://pypi.python.org/simple/parallel-ssh/), version: 0.70
    Found link https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.80.0.tar.gz#md5=3cddeaa0aedf68e2fdfa73c81ed21e56 (from https://pypi.python.org/simple/parallel-ssh/), version: 0.80.0
  Using version 0.80.0 (newest of versions: 0.80.0, 0.70.4, 0.70.3, 0.70.2, 0.70.1, 0.70, 0.61, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1)
  Downloading parallel-ssh-0.80.0.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/p/parallel-ssh/parallel-ssh-0.80.0.tar.gz#md5=3cddeaa0aedf68e2fdfa73c81ed21e56 (from https://pypi.python.org/simple/parallel-ssh/)
  Running setup.py (path:/tmp/pip-build-feBbyp/parallel-ssh/setup.py) egg_info for package parallel-ssh
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-feBbyp/parallel-ssh/setup.py", line 26, in <module>
        install_requires = open('requirements.txt').readlines(),
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-feBbyp/parallel-ssh/setup.py", line 26, in <module>

    install_requires = open('requirements.txt').readlines(),

IOError: [Errno 2] No such file or directory: 'requirements.txt'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-feBbyp/parallel-ssh
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-feBbyp/parallel-ssh

**Comment by pkittenis** [comment]
Thanks for raising!

Resolved by `0.80.1` release:

```bash
# pip install -U parallel-ssh --no-cache-dir
Collecting parallel-ssh
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading parallel-ssh-0.80.1.tar.gz
Requirement already up-to-date: paramiko in /usr/local/lib/python2.7/dist-packages (from parallel-ssh)
Requirement already up-to-date: gevent in /usr/local/lib/python2.7/dist-packages (from parallel-ssh)
Requirement already up-to-date: ecdsa>=0.11 in /usr/local/lib/python2.7/dist-packages (from paramiko->parallel-ssh)
Requirement already up-to-date: pycrypto!=2.4,>=2.1 in /usr/local/lib/python2.7/dist-packages (from paramiko->parallel-ssh)
Requirement already up-to-date: greenlet>=0.4.7 in /usr/local/lib/python2.7/dist-packages (from gevent->parallel-ssh)
Installing collected packages: parallel-ssh
  Running setup.py install for parallel-ssh
Successfully installed parallel-ssh-0.80.1
```

**Comment by nitintt1991** [comment]
Hello I faced similar issue while trying to run the command for jenkinsapi:
 sudo pip install jenkinsapi
Downloading jenkinsapi-0.3.4.tar.gz (44kB): 44kB downloaded
  Running setup.py egg_info for package jenkinsapi
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build/jenkinsapi/setup.py", line 35, in <module>
        for line in open('requirements/dev-requirements.txt')
    IOError: [Errno 2] No such file or directory: 'requirements/dev-requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build/jenkinsapi/setup.py", line 35, in <module>

    for line in open('requirements/dev-requirements.txt')

IOError: [Errno 2] No such file or directory: 'requirements/dev-requirements.txt'
Could I get some help here?

**Comment by pkittenis** [comment]
Best to raise an issue on the jenkinsapi project.
