### ISSUE TITLE
pssh reports an error when copying files to remote hosts (even though it works)

### ISSUE THREAD

**Issue by Caid11** [pkittenis/parallel-ssh#41]
Hi,

I have a Python script that uses pssh to copy a bash script to remote hosts, then execute it. For some reason, when it copies the script over using `client.copy_file`, it throws the following error:

`ERROR:pssh.ssh_client:Error occured creating directory on [host] - [Errno 2] No such file`

Even though it throws this error, the script still successfully copies and executes. I'm not sure if I'm using it incorrectly, or it's a bug. Either way, I thought it might be good to put it out there.

Thanks!

**Comment by pkittenis** [comment]
Could you please give an example script with code that throws this error?

**Comment by Caid11** [comment]
Sure. The code below throws the error.

On further examination, it appears that the call to `client.pool.join()` at the end is what is causing it to throw the error.

```
from pssh import ParallelSSHClient
from paramiko import RSAKey
import logging

logging.basicConfig()

hosts = [host_ip]

ssh_key = RSAKey.from_private_key_file(ssh_key_path)

ssh_client = ParallelSSHClient(hosts, pkey=ssh_key, user=user)

ssh_client.copy_file(local_script_path, remote_script_path)

# If I take this line out, the error isn't thrown.
ssh_client.pool.join()
```

**Comment by pkittenis** [comment]
And what are the values of `local_script_path` and `remote_script_path`?

**Comment by Caid11** [comment]
In my case, they are identical paths, both point to the /tmp directory. For the specific code above, the path I used for both was /tmp/foo.sh.

**Comment by pkittenis** [comment]
Confirmed as bug with attempt to create missing directory - thanks for raising. Bug is caused by absolute path in remote file destination.
