### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by gipi** [pkittenis/parallel-ssh#54]
I'm trying to use ``parallel-ssh`` in a project of mine and all it's working fine, only I noticed that if I launch the command ``lsblk`` in the remote side an exception is raised

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/deplopy/deplopy/deplopy/deplopy.py", line 83, in <module>
    for stdout in output[host]['stdout']:
  File "/opt/deplopy/.virtualenv/local/lib/python2.7/site-packages/pssh/ssh_client.py", line 240, in _read_output_buffer
    output = line.strip().decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

If I log in the machine with ``ssh`` all it's working fine, the character that is causing trouble is the
first in the third line of the output

```
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
vda    254:0    0  20G  0 disk
└─vda1 254:1    0  20G  0 part /
```

i.e. ``└``, If I remove ``decode('ascii')`` from the ``ssh_client`` code all it's working fine.

I'm not proposing a patch because I'm not sure what the ``decode`` function should do in this case, my guess is that is for terminal compatibility.

Seems strange to me that I'm the first to encounter such issue, but I searched on github without any luck, so here we are.

**Comment by pkittenis** [comment]
Thanks for raising! Fixed in master branch.

NB - the ascii decode was added for forwards compatibility with py3 which uses byte buffers by default which need decoding into strings. 

Changing the decode to utf8 seems to resolve the issue though obviously exotic terminal encodings may still cause issues. 

Perhaps the client should check character encoding via $LANG and convert accordingly.. Some testing if you have non utf8 or ascii terminals lying around would be appreciated.

**Comment by pkittenis** [comment]
From latest master branch:

```
In [1]: from pssh import ParallelSSHClient

In [2]: client = ParallelSSHClient(['localhost'])

In [3]: output = client.run_command('lsblk')

In [4]: for line in output['localhost']['stdout']: print line
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 238.5G  0 disk
├─sda1   8:1    0  62.7G  0 part
├─sda2   8:2    0   1.9G  0 part
└─sda3   8:3    0 173.9G  0 part /
sr0     11:0    1  1024M  0 rom
```

```pip install https://github.com/pkittenis/parallel-ssh/archive/master.zip```
