### ISSUE TITLE
Unable to get stdout and exit code for copy_file

### ISSUE THREAD

**Issue by liusztc09** [pkittenis/parallel-ssh#60]
Hi pkittenis,

I checked the documentation but didn't find a way to retrieve the stdout while using copy_file. It return a greenlet and I want to print out the stdout. Is there a way to do it in the current version?

Thanks,
David

**Comment by pkittenis** [comment]
Hi David,

Please use [Google group](https://groups.google.com/forum/#!forum/parallelssh) for questions on using the library - issue tracker is for issues with the code.

To answer your question, there is no output nor exit codes provided by the SFTP protocol. Indication of error with the SFTP command is any exceptions thrown.
