### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by sunshinekitty** [pkittenis/parallel-ssh#61]
Hi,

When getting output that contains latin-1 encoded characters it's not possible to iterate through them, can an argument be added to `run_command`/`exec_command` to specify encoding type to decode? Unless you know of a better way I can submit a PR.

Stack trace:
```
Traceback (most recent call last):
  File "shared/common.py", line 106, in concurrent_ssh_command
    for line in out['stdout']:
  File "build/bdist.linux-x86_64/egg/pssh/pssh_client.py", line 550, in _read_buff_ex_code
  File "build/bdist.linux-x86_64/egg/pssh/ssh_client.py", line 245, in _read_output_buffer
  File "lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 178: invalid continuation byte
```

Relevant code:
```
client = ParallelSSHClient(hosts, timeout=3)
output = client.run_command(command)
client.pool.join()
to_return = []
for host, out in output.iteritems():
    stdout = []
    stderr = []
    for line in out['stdout']:
        stdout.append(str(line))
    for line in out['stderr']:
        stderr.append(str(line))
    to_return.append({host: {"stdout": stdout, "stderr": stderr}})
return to_return
```

**Comment by pkittenis** [comment]
Hi,

Thanks for raising! Yes, encodings that cannot be represented by utf8 will break output reading.

A *better way*, though not one I have tried, would be to use $LANG to get current terminal encoding and make `.decode` use that instead.

Could you please show sample output that is currently breaking it - can then test if this solution would work.

**Comment by sunshinekitty** [comment]
I'm not sure $LANG env variable would work, mine is set to en_US.UTF-8 so it would still use utf-8.  An example character is é

You can reproduce this by putting é in a text file on a remote server and then have parallelssh run a cat on that file.

**Comment by pkittenis** [comment]
Thanks - with that output the error cannot be reproduced. It looks like a bug in the output gathering code rather than parallel-ssh.

This works:

```
output = client.run_command("echo 'é'")
for host, out in output.iteritems():
    for line in out['stdout']: print line
é
```

This doesn't:

```
output = client.run_command("echo 'é'")
for host, out in output.iteritems():
    for line in out['stdout']: print str(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 0: ordinal not in range(128)
```

Remove the `str(line)` and it should work. Wrapping output as str is not needed, the library decodes to unicode by default.

**Comment by sunshinekitty** [comment]
Doh, thought I had tried that.  I'll close this out, thank you.

**Comment by pkittenis** [comment]
No worries, glad it works :)

Will still raise an issue to get $LANG implemented - not high priority atm though.
