### ISSUE TITLE
copy_file is not creating folders that part of the path on remote host nor raising exception

### ISSUE THREAD

**Issue by bexp** [pkittenis/parallel-ssh#64]
Hi, according to a doc copy_file should be able to create missing folder
> Remote directories in remote_file that do not exist will be created as long as permissions allow.

I don't see this is happening. I used same credentials for python script as default ssh client
to verify I can create folder manually on remote. 

this is output from the pssh:
>Error occured copying file 1 to remote destination mysuperhost:/mnt/cache/purge_requests/1 - >[Errno 2] No such file

local file also exists, and copy_file succeeded with hosts which have remote folder already created.
would be nice to add some exception for that case. 

This is the code I'm using right now:
```
    output = ssh_client.copy_file(src, dst)
    ssh_client.pool.join()
    for cmd in output:
        try:
            cmd_out = cmd.get()
            print 'upload result ', cmd.exception
        except (ConnectionErrorException, AuthenticationException,\
                UnknownHostException, SSHException ) as e:
            print("Unexpected error:{} in host {}".format(e,  e.args[1]))
            print "*** removing errorneous hostname from list ", e.args[1]
            ssh_client.hosts.remove(e.args[1])
        except Exception as e:
            print 'upload exception ', str(e)
            ssh_client.hosts.remove(e.args[1])
```

**Comment by pkittenis** [comment]
Indeed, this is a bug with multiple directories in target `remote_file`. Weirdly enough, there is a test for exactly this - not a good one obviously :)

The [branch referenced above contains a fix|https://github.com/pkittenis/parallel-ssh/compare/copy_file_multi_dir_fix], feel free to install if this is a blocker for you, though not releasing  before fixing tests.

It should also be raising exception on permission errors, yes, that will be in next point release at it's an API change.

**Comment by bexp** [comment]
thanks for quick fix in branch. I will wait for release .

**Comment by pkittenis** [comment]
`0.92.2` contains this fix. Exception on permissions errors will be in a new release as it's API change, can watch #65 for that.

Thanks again for raising :+1:
